#!/usr/bin/env ruby -w -U
# encoding: UTF-8
# (c) ANB Andrew Bizyaev

require_relative 'error'
require 'date'

# Foto tools
module FTools
  # batch EXIF tags setter
  class Tagger
    attr_reader :script_name

    def initialize(script_name: 'script.txt', memo: 'Generated by ftools')
      @script_name = script_name
      create_script(memo)
    end

    def create_script(memo)
      @script = File.open(@script_name, 'w+:utf-8')
      @script.puts '# exiftool script for batch tag operations'
      @script.puts "# usage: exiftool -@ #{@script_name}"
      @script.puts "# #{memo}"
    rescue => e
      raise FTools::ExiftoolTagger, "creating exiftool script - #{e.message}"
    end

    def add_to_script(ftfile: '', tags: {}, options: [])
      # MWG:Keywords = IPTC:Keywords, XMP-dc:Subject
      tags[:keywords].each do |o|
        @script.puts %Q{-MWG:Keywords-=#{o}}
        @script.puts %Q{-MWG:Keywords+=#{o}}
      end
      # collection_name and XPSubject
      @script.puts %Q{-XMP:CollectionName-=#{tags[:collection_name]}}
      @script.puts %Q{-XMP:CollectionName+=#{tags[:collection_name]}}
      # collection_uri
      @script.puts %Q{-XMP:CollectionURI-=#{tags[:collection_uri]}}
      @script.puts %Q{-XMP:CollectionURI+=#{tags[:collection_uri]}}
      @script.puts %Q{-IPTC:CodedCharacterSet=#{tags[:coded_character_set]}}
      @script.puts %Q{-EXIF:ModifyDate=#{tags[:modify_date]}}
      @script.puts %Q{#{ftfile}}
      # General options
      options.each { |o| @script.puts "#{o}" }
      @script.puts %Q{-execute}
      @script.puts

    rescue => e
      raise FTools::ExiftoolTagger, "adding instructions to exiftool script - #{e.message}"
    end

    def close_script
      @script.close
    rescue => e
      raise FTools::ExiftoolTagger, "closing exiftool script - #{e.message}"
    end
  end
end
